name: Make release

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    name: Build source distribution and wheel
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
    - name: Install Python 3.x
      uses: actions/setup-python@v5
      with:
        python-version: 3.x
    - name: Install build
      run: pip install build
    - name: Build sdist & wheel
      run: python -m build
    - name: Save sdist & wheel
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: |
          dist/*.tar.gz
          dist/*.whl
